version: '3'
services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passw
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
      
  web:
    build: .
    ports:
      - "5000:5000"
    links:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
